name: Project Tree
on:
  [push]

jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects_tree

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: flutter build web --web-renderer html --release
    - name: Download Artifact for Managment 
        uses: actions/download-artifact@v2
        with:
          name: Managment-web
    - name: Download  Artifact for MasterBurger
        uses: actions/download-artifact@v2
        with:
          name: MasterBorger-web
    - name: Download  Artifact for LinkTree
        uses: actions/download-artifact@v2
        with:
          name: LinkTree-web
    - name: Download Artifact for Expenses
        uses: actions/download-artifact@v2
        with:
          name: Expenses-web
    - name: Download Artifact for Forms
        uses: actions/download-artifact@v2
        with:
          name: Forms-web
    - shell: bash
      run: |
        ls -la ../ 
        ls -la
    # - name: Deploy 🚀
    #   uses: JamesIves/github-pages-deploy-action@4.1.3
    #   with:
    #     branch: gh-pages # The branch the action should deploy to.
    #     folder: projects_tree/build/web # The folder the action should deploy.